version: '3.5'
services:
  webserver_porto:
    image: nginx:alpine
    container_name: webserver_porto
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
     - ./:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
     - efo_networks
    command: [nginx-debug, '-g', 'daemon off;']
  porto_web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: porto_web
    networks:
      - app-network
    ports:
      - 8099:3000
networks:
  app-network:
    name: efo_networks
    driver: bridge